[package]
name = "prml-generic-asset-rpc"
version = "2.0.0"
authors = ["Centrality Developers <support@centrality.ai>"]
edition = "2018"
license = "GPL-3.0"
repository = "https://github.com/plugblockchain/plug-blockchain/"
description = "RPC interface for the generic asset module."

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.5" }
jsonrpc-core = "15.0.0"
jsonrpc-core-client = "15.0.0"
jsonrpc-derive = "15.0.0"
serde = { version = "1.0.101", features = ["derive"] }
sp-api = { version = "2.0.0" }
sp-blockchain = { version = "2.0.0" }
sp-core = { version = "2.0.0" }
sp-rpc = { version = "2.0.0" }
sp-runtime = { version = "2.0.0" }
prml-generic-asset = { path = "../" }
prml-generic-asset-rpc-runtime-api = { path = "runtime-api" }
