[package]
name = "frame-benchmarking-cli"
version = "2.0.0-alpha.5"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "CLI for benchmarking FRAME"

[dependencies]
<<<<<<< HEAD
frame-benchmarking = { version = "2.0.0-alpha.4", path = "../../../frame/benchmarking" }
sp-core = { version = "2.0.0-alpha.4", path = "../../../primitives/core" }
sc-service = { version = "0.8.0-alpha.4", default-features = false, path = "../../../client/service" }
sc-cli = { version = "0.8.0-alpha.4", path = "../../../client/cli" }
sc-client = { version = "0.8.0-alpha.4", path = "../../../client" }
sc-client-db = { version = "0.8.0-alpha.4", path = "../../../client/db" }
sc-executor = { version = "0.8.0-alpha.4", path = "../../../client/executor" }
sp-runtime = { version = "2.0.0-alpha.4", path = "../../../primitives/runtime" }
sp-state-machine = { version = "0.8.0-alpha.4", path = "../../../primitives/state-machine" }
=======
frame-benchmarking = { version = "2.0.0-alpha.5", path = "../../../frame/benchmarking" }
sp-core = { version = "2.0.0-alpha.5", path = "../../../primitives/core" }
sc-service = { version = "0.8.0-alpha.5", default-features = false, path = "../../../client/service" }
sc-cli = { version = "0.8.0-alpha.5", path = "../../../client/cli" }
sc-client = { version = "0.8.0-alpha.5", path = "../../../client" }
sc-client-db = { version = "0.8.0-alpha.5", path = "../../../client/db" }
sc-executor = { version = "0.8.0-alpha.5", path = "../../../client/executor" }
sp-externalities = { version = "0.8.0-alpha.5", path = "../../../primitives/externalities" }
sp-runtime = { version = "2.0.0-alpha.5", path = "../../../primitives/runtime" }
sp-state-machine = { version = "0.8.0-alpha.5", path = "../../../primitives/state-machine" }
>>>>>>> d9e989a4b... Releasing 2.0.0-alpha.5 (#5340)
structopt = "0.3.8"
codec = { version = "1.2.0", package = "parity-scale-codec" }

[features]
default = ["rocksdb"]
rocksdb = ["sc-client-db/kvdb-rocksdb"]
