[package]
name = "substrate-test-utils"
<<<<<<< HEAD
version = "2.0.0-alpha.3"
=======
version = "2.0.0-alpha.5"
>>>>>>> d9e989a4b... Releasing 2.0.0-alpha.5 (#5340)
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
